# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mundial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidoSeleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='pronostico',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partido',
            name='resultado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mundial.Resultado'),
        ),
        migrations.AlterField(
            model_name='pronostico',
            name='resultado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mundial.Resultado'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='ganador_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='goles_local',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='goles_visitante',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='penales_local',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='penales_visitante',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='partidoseleccion',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundial.Partido'),
        ),
        migrations.AddField(
            model_name='partidoseleccion',
            name='seleccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundial.Seleccion'),
        ),
        migrations.AddField(
            model_name='partido',
            name='partido_selecciones',
            field=models.ManyToManyField(through='mundial.PartidoSeleccion', to='mundial.Seleccion'),
        ),
    ]
