# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0003_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
